### ISSUE TITLE
Issue: Determine actions to take when oracle price fails to load

### ISSUE THREAD

**Issue by Ryang-21** [script3/auctioneer-bot#10]
- Oracles prices have the possibility of failing to return. In this event new user liquidations, liquidation fills, and bad debt fills will fail due to being unable to calculate the effective collateral and liabilities of the user position or auction.
- Possible solutions are to continue retrying the user liquidation creation or fill until the oracle price is restored. 
- Auctions fills are potentially possible if the filler is able to repay all liabilities of the auction and have no existing liability positions

**Comment by mootz12** [comment]
The places `loadPoolOracle` are mostly wrapped in appropriate error handling.

A few edge cases that need to be patched:

1. https://github.com/script3/auctioneer-bot/blob/main/src/bidder.ts#L33
The for loop processing auctions from DB on each block needs error handling wrapped around it to ensure, if one auction has an issue for some reason, the rest of the ongoing auctions can be safely processed.

Auctions are added to this DB based only on the incoming event and bot configuration, so we can trust that auctions will be safely added to the DB.

2. https://github.com/script3/auctioneer-bot/blob/main/src/bidder_submitter.ts#L179
We should just stop deleting auction entries from the DB if we are unable to submit them, it opens too many edge cases for upstream things to fail that cause us to incorrectly drop an auction.

Secondly, we should add some slow down mechanism to the submitter's retry loop (say, 1 second), to ensure that something doesn't spam retry for a momentary problem. I don't think this is an issue for the event queue, but we could also port this code to the event retry loop as well.
